import type { Resource } from './types'

// Shared resource catalog. Lessons reference these entries, so a link is fixed
// in one place. Run `npm run check:links` after
// adding or changing a URL — it confirms every link (and every YouTube video)
// still resolves.

const yt = (id: string) => `https://www.youtube.com/watch?v=${id}`

export const R = {
  // ── Books ──────────────────────────────────────────────────────────────────
  businessValueDevRel: {
    title: 'The Business Value of Developer Relations',
    by: 'Mary Thengvall (Apress)',
    url: 'https://link.springer.com/book/10.1007/978-1-4842-3748-9',
    kind: 'book',
    note: 'The standard text on how DevRel creates — and proves — value for a company.',
  },
  devRelBook: {
    title: 'Developer Relations: How to Build and Grow a Successful Developer Program',
    by: 'Caroline Lewko & James Parton (Apress)',
    url: 'https://link.springer.com/book/10.1007/978-1-4842-7164-3',
    kind: 'book',
    note: 'Introduces the Developer Journey framework and how to structure a program around it.',
  },
  artOfCommunity: {
    title: 'The Art of Community',
    by: 'Jono Bacon (O’Reilly)',
    url: 'https://www.oreilly.com/library/view/the-art-of/9781449337506/',
    kind: 'book',
    note: 'A classic on building, governing and growing communities, drawn from open source.',
  },
  peoplePowered: {
    title: 'People Powered',
    by: 'Jono Bacon (HarperCollins Leadership)',
    url: 'https://www.jonobacon.com/books/peoplepowered/',
    kind: 'book',
    note: 'A practical framework for community strategy, including the three community types.',
  },
  getTogether: {
    title: 'Get Together: How to Build a Community with Your People',
    by: 'Bailey Richardson, Kevin Huynh & Kai Elmer Sotto (Stripe Press)',
    url: 'https://press.stripe.com/get-together',
    kind: 'book',
    note: 'Short, story-driven guide to starting a community around a shared interest.',
  },
  docsForDevelopers: {
    title: 'Docs for Developers: An Engineer’s Field Guide to Technical Writing',
    by: 'Jared Bhatti, Zachary Sarah Corleissen, Jen Lambourne, David Nunez & Heidi Waterhouse (Apress)',
    url: 'https://docsfordevelopers.com/',
    kind: 'book',
    note: 'Takes one fictional product from zero docs to a full doc set — the most practical docs book.',
  },
  workingInPublic: {
    title: 'Working in Public: The Making and Maintenance of Open Source Software',
    by: 'Nadia Eghbal (Stripe Press)',
    url: 'https://press.stripe.com/working-in-public',
    kind: 'book',
    note: 'How modern open source actually works — and why maintainers, not contributors, are the bottleneck.',
  },
  producingOSS: {
    title: 'Producing Open Source Software',
    by: 'Karl Fogel',
    url: 'https://producingoss.com/',
    kind: 'book',
    free: true,
    note: 'Free online book on running a healthy open source project — governance, communication, money.',
  },
  proGit: {
    title: 'Pro Git',
    by: 'Scott Chacon & Ben Straub',
    url: 'https://git-scm.com/book/en/v2',
    kind: 'book',
    free: true,
    note: 'The free, official Git book. Chapters 1–3 cover everything most DevRel work needs.',
  },
  resonate: {
    title: 'Resonate: Present Visual Stories that Transform Audiences',
    by: 'Nancy Duarte',
    url: 'https://www.duarte.com/resources/books/resonate/',
    kind: 'book',
    note: 'The talk-structure book behind "what is vs what could be". Readable free on Duarte’s site.',
  },
  talkLikeTed: {
    title: 'TED Talks: The Official TED Guide to Public Speaking',
    by: 'Chris Anderson',
    url: 'https://www.ted.com/read/ted-talks-the-official-ted-guide-to-public-speaking',
    kind: 'book',
    note: 'How to find the one idea your talk is about and build everything around it.',
  },
  demystifyingPublicSpeaking: {
    title: 'Demystifying Public Speaking',
    by: 'Lara Hogan (A Book Apart)',
    url: 'https://larahogan.me/speaking/',
    kind: 'book',
    note: 'Short, practical and written by an engineering leader — ideal for first-time speakers.',
  },
  everybodyWrites: {
    title: 'Everybody Writes',
    by: 'Ann Handley (Wiley)',
    url: 'https://annhandley.com/books/',
    kind: 'book',
    note: 'Writing habits and editing rules for content that people actually finish.',
  },
  showYourWork: {
    title: 'Show Your Work!',
    by: 'Austin Kleon (Workman)',
    url: 'https://austinkleon.com/show-your-work/',
    kind: 'book',
    note: 'Ten short principles for sharing your process — the philosophy behind building in public.',
  },
  codingCareerHandbook: {
    title: 'The Coding Career Handbook',
    by: 'Shawn "swyx" Wang',
    url: 'https://learninpublic.org/',
    kind: 'book',
    note: 'Career strategy for developers, built around learning in public. Many DevRel careers start here.',
  },
  storytellingWithData: {
    title: 'Storytelling with Data',
    by: 'Cole Nussbaumer Knaflic (Wiley)',
    url: 'https://www.storytellingwithdata.com/books',
    kind: 'book',
    note: 'How to turn numbers into charts leadership understands in one glance.',
  },
  measureWhatMatters: {
    title: 'Measure What Matters',
    by: 'John Doerr (Portfolio)',
    url: 'https://www.whatmatters.com/the-book',
    kind: 'book',
    note: 'The OKR book. Use it to set DevRel goals that connect to company goals.',
  },
  leanAnalytics: {
    title: 'Lean Analytics',
    by: 'Alistair Croll & Benjamin Yoskovitz (O’Reilly)',
    url: 'https://leananalyticsbook.com/',
    kind: 'book',
    note: 'Choosing the "one metric that matters" for the stage you’re in.',
  },
  momTest: {
    title: 'The Mom Test',
    by: 'Rob Fitzpatrick',
    url: 'https://www.momtestbook.com/',
    kind: 'book',
    note: 'How to ask developers questions that get honest answers instead of polite ones.',
  },
  devMarketingDoesNotExist: {
    title: 'Developer Marketing Does Not Exist',
    by: 'Adam DuVander',
    url: 'https://everydeveloper.com/developer-marketing/book/',
    kind: 'book',
    note: 'Why marketing to developers is really education — and how to do it.',
  },
  crucialConversations: {
    title: 'Crucial Conversations',
    by: 'Joseph Grenny, Kerry Patterson, Ron McMillan, Al Switzler & Emily Gregory (McGraw Hill)',
    url: 'https://cruciallearning.com/crucial-conversations-book/',
    kind: 'book',
    note: 'A framework for high-stakes conversations — useful for moderation and stakeholder disputes.',
  },
  managersPath: {
    title: 'The Manager’s Path',
    by: 'Camille Fournier (O’Reilly)',
    url: 'https://www.oreilly.com/library/view/the-managers-path/9781491973882/',
    kind: 'book',
    note: 'The tech-leadership ladder from mentor to exec. Transfers directly to DevRel team leadership.',
  },
  developerAdvocateBook: {
    title: 'Developer, Advocate!',
    by: 'Geertjan Wielenga (Packt)',
    url: 'https://www.oreilly.com/library/view/developer-advocate/9781789138740/',
    kind: 'book',
    note: 'Interviews with well-known developer advocates on how they got in and what the work is really like.',
  },
  pragmaticProgrammer: {
    title: 'The Pragmatic Programmer (20th Anniversary Edition)',
    by: 'David Thomas & Andrew Hunt (Addison-Wesley)',
    url: 'https://pragprog.com/titles/tpp20/the-pragmatic-programmer-20th-anniversary-edition/',
    kind: 'book',
    note: 'How working engineers think. Reading it makes you a better peer to your audience.',
  },

  // ── Guides & articles ──────────────────────────────────────────────────────
  googleTechWriting: {
    title: 'Technical Writing Courses',
    by: 'Google for Developers',
    url: 'https://developers.google.com/tech-writing',
    kind: 'course',
    free: true,
    note: 'Two free self-paced courses. The best starting point for clear technical writing.',
  },
  googleStyleGuide: {
    title: 'Google Developer Documentation Style Guide',
    by: 'Google',
    url: 'https://developers.google.com/style',
    kind: 'guide',
    free: true,
    note: 'The reference for voice, tone, formatting and word choice in developer docs.',
  },
  msStyleGuide: {
    title: 'Microsoft Writing Style Guide',
    by: 'Microsoft',
    url: 'https://learn.microsoft.com/en-us/style-guide/welcome/',
    kind: 'guide',
    free: true,
    note: 'Especially strong on plain, warm, direct voice — "write like you speak".',
  },
  diataxis: {
    title: 'Diátaxis — a systematic approach to technical documentation',
    by: 'Daniele Procida',
    url: 'https://diataxis.fr/',
    kind: 'guide',
    free: true,
    note: 'Tutorials, how-tos, reference, explanation: the four doc types and why mixing them fails.',
  },
  writeTheDocsGuide: {
    title: 'Write the Docs Guide',
    by: 'Write the Docs community',
    url: 'https://www.writethedocs.org/guide/',
    kind: 'guide',
    free: true,
    note: 'Community-written guide to docs as code, doc types, and building a docs culture.',
  },
  writeTheDocs: {
    title: 'Write the Docs',
    by: 'Community & conference',
    url: 'https://www.writethedocs.org/',
    kind: 'community',
    free: true,
    note: 'The global community for people who care about documentation. Great Slack and talks archive.',
  },
  goodDocsProject: {
    title: 'The Good Docs Project — templates',
    by: 'The Good Docs Project',
    url: 'https://www.thegooddocsproject.dev/',
    kind: 'tool',
    free: true,
    note: 'Open source templates for READMEs, tutorials, how-tos, API references and more.',
  },
  openSourceGuides: {
    title: 'Open Source Guides',
    by: 'GitHub',
    url: 'https://opensource.guide/',
    kind: 'guide',
    free: true,
    note: 'Short guides on contributing, starting, maintaining and funding open source projects.',
  },
  osgHowToContribute: {
    title: 'How to Contribute to Open Source',
    by: 'Open Source Guides (GitHub)',
    url: 'https://opensource.guide/how-to-contribute/',
    kind: 'guide',
    free: true,
  },
  osgBuildingCommunity: {
    title: 'Building Welcoming Communities',
    by: 'Open Source Guides (GitHub)',
    url: 'https://opensource.guide/building-community/',
    kind: 'guide',
    free: true,
  },
  osgBestPractices: {
    title: 'Best Practices for Maintainers',
    by: 'Open Source Guides (GitHub)',
    url: 'https://opensource.guide/best-practices/',
    kind: 'guide',
    free: true,
  },
  osgLeadership: {
    title: 'Leadership and Governance',
    by: 'Open Source Guides (GitHub)',
    url: 'https://opensource.guide/leadership-and-governance/',
    kind: 'guide',
    free: true,
  },
  osgLegal: {
    title: 'The Legal Side of Open Source',
    by: 'Open Source Guides (GitHub)',
    url: 'https://opensource.guide/legal/',
    kind: 'guide',
    free: true,
  },
  osgMetrics: {
    title: 'Open Source Metrics',
    by: 'Open Source Guides (GitHub)',
    url: 'https://opensource.guide/metrics/',
    kind: 'guide',
    free: true,
  },
  osgCoc: {
    title: 'Your Code of Conduct',
    by: 'Open Source Guides (GitHub)',
    url: 'https://opensource.guide/code-of-conduct/',
    kind: 'guide',
    free: true,
  },
  contributorCovenant: {
    title: 'Contributor Covenant',
    by: 'Organization for Ethical Source',
    url: 'https://www.contributor-covenant.org/',
    kind: 'tool',
    free: true,
    note: 'The most widely adopted code of conduct template for developer communities.',
  },
  chooseALicense: {
    title: 'Choose a License',
    by: 'GitHub',
    url: 'https://choosealicense.com/',
    kind: 'tool',
    free: true,
    note: 'Plain-English comparison of open source licenses, with the full texts.',
  },
  osiLicenses: {
    title: 'OSI Approved Licenses',
    by: 'Open Source Initiative',
    url: 'https://opensource.org/licenses',
    kind: 'guide',
    free: true,
    note: 'The canonical list of licenses that meet the Open Source Definition.',
  },
  todoGroup: {
    title: 'TODO Group — OSPO guides',
    by: 'Linux Foundation',
    url: 'https://todogroup.org/',
    kind: 'guide',
    free: true,
    note: 'Guides for company Open Source Program Offices: strategy, policy, metrics.',
  },
  chaoss: {
    title: 'CHAOSS — Community Health Analytics in Open Source Software',
    by: 'Linux Foundation',
    url: 'https://chaoss.community/',
    kind: 'guide',
    free: true,
    note: 'Open, well-defined community health metrics you can adopt instead of inventing your own.',
  },
  apacheHowItWorks: {
    title: 'How the Apache Software Foundation Works',
    by: 'Apache Software Foundation',
    url: 'https://www.apache.org/foundation/how-it-works/',
    kind: 'guide',
    free: true,
    note: 'Meritocracy, PMCs and "community over code" — governance from the source.',
  },
  cncfProjects: {
    title: 'CNCF Project Maturity Levels',
    by: 'Cloud Native Computing Foundation',
    url: 'https://www.cncf.io/project-metrics/',
    kind: 'guide',
    free: true,
    note: 'How a foundation graduates projects from sandbox to incubating to graduated.',
  },
  goodFirstIssue: {
    title: 'Good First Issue',
    by: 'goodfirstissue.dev',
    url: 'https://goodfirstissue.dev/',
    kind: 'tool',
    free: true,
    note: 'Curated beginner-friendly issues across popular projects.',
  },
  firstContributions: {
    title: 'First Contributions',
    by: 'firstcontributions',
    url: 'https://github.com/firstcontributions/first-contributions',
    kind: 'guide',
    free: true,
    note: 'A hands-on repo that walks you through your first pull request.',
  },
  githubSkills: {
    title: 'GitHub Skills',
    by: 'GitHub',
    url: 'https://skills.github.com/',
    kind: 'course',
    free: true,
    note: 'Interactive courses that run inside real GitHub repositories.',
  },
  githubIssuesDocs: {
    title: 'GitHub Issues documentation',
    by: 'GitHub Docs',
    url: 'https://docs.github.com/en/issues',
    kind: 'guide',
    free: true,
  },
  githubLabelsDocs: {
    title: 'Managing labels',
    by: 'GitHub Docs',
    url: 'https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels',
    kind: 'guide',
    free: true,
  },
  githubDiscussionsDocs: {
    title: 'GitHub Discussions documentation',
    by: 'GitHub Docs',
    url: 'https://docs.github.com/en/discussions',
    kind: 'guide',
    free: true,
  },
  githubPRDocs: {
    title: 'About pull requests',
    by: 'GitHub Docs',
    url: 'https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests',
    kind: 'guide',
    free: true,
  },
  linearMethod: {
    title: 'The Linear Method',
    by: 'Linear',
    url: 'https://linear.app/method',
    kind: 'guide',
    free: true,
    note: 'Opinionated principles for issue tracking and product development that stays fast.',
  },
  missingSemester: {
    title: 'The Missing Semester of Your CS Education',
    by: 'MIT',
    url: 'https://missing.csail.mit.edu/',
    kind: 'course',
    free: true,
    note: 'Shell, editors, Git, debugging — the tool fluency courses usually skip.',
  },
  vscodeDocs: {
    title: 'Visual Studio Code documentation',
    by: 'Microsoft',
    url: 'https://code.visualstudio.com/docs',
    kind: 'guide',
    free: true,
  },
  freeCodeCamp: {
    title: 'freeCodeCamp',
    by: 'freeCodeCamp.org',
    url: 'https://www.freecodecamp.org/',
    kind: 'course',
    free: true,
    note: 'Free, project-based curriculum for web development, Python, and more.',
  },
  odinProject: {
    title: 'The Odin Project',
    by: 'The Odin Project',
    url: 'https://www.theodinproject.com/',
    kind: 'course',
    free: true,
    note: 'Free full-stack curriculum built around real projects.',
  },
  cs50: {
    title: 'CS50: Introduction to Computer Science',
    by: 'Harvard University',
    url: 'https://cs50.harvard.edu/x/',
    kind: 'course',
    free: true,
    note: 'The best free programming fundamentals course. Challenging and worth it.',
  },
  mdnHttp: {
    title: 'An overview of HTTP',
    by: 'MDN Web Docs',
    url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview',
    kind: 'guide',
    free: true,
    note: 'Requests, responses, methods and status codes — the ground every web API stands on.',
  },
  postmanLearning: {
    title: 'Postman Learning Center',
    by: 'Postman',
    url: 'https://learning.postman.com/',
    kind: 'guide',
    free: true,
    note: 'Hands-on guides for exploring, testing and documenting APIs.',
  },
  graphqlLearn: {
    title: 'Learn GraphQL',
    by: 'graphql.org',
    url: 'https://graphql.org/learn/',
    kind: 'guide',
    free: true,
  },
  googleApiDesign: {
    title: 'API Design Guide',
    by: 'Google Cloud',
    url: 'https://cloud.google.com/apis/design',
    kind: 'guide',
    free: true,
    note: 'How Google designs consistent APIs — resource names, methods, errors.',
  },
  dockerGetStarted: {
    title: 'Get started with Docker',
    by: 'Docker Docs',
    url: 'https://docs.docker.com/get-started/',
    kind: 'guide',
    free: true,
  },
  k8sBasics: {
    title: 'Learn Kubernetes Basics',
    by: 'Kubernetes Docs',
    url: 'https://kubernetes.io/docs/tutorials/kubernetes-basics/',
    kind: 'guide',
    free: true,
  },
  gcpSkillsBoost: {
    title: 'Google Cloud Skills Boost',
    by: 'Google Cloud',
    url: 'https://www.cloudskillsboost.google/',
    kind: 'course',
    note: 'Hands-on labs in real cloud consoles. Many beginner paths are free.',
  },
  awsSkillBuilder: {
    title: 'AWS Skill Builder',
    by: 'Amazon Web Services',
    url: 'https://skillbuilder.aws/',
    kind: 'course',
    note: 'Includes the free Cloud Practitioner Essentials course.',
  },
  soSurvey: {
    title: 'Stack Overflow Developer Survey',
    by: 'Stack Overflow',
    url: 'https://survey.stackoverflow.co/',
    kind: 'article',
    free: true,
    note: 'Annual data on what developers use, learn and care about. Know your audience.',
  },
  nngJourneyMapping: {
    title: 'Journey Mapping 101',
    by: 'Nielsen Norman Group',
    url: 'https://www.nngroup.com/articles/journey-mapping-101/',
    kind: 'article',
    free: true,
  },
  nngErrorMessages: {
    title: 'Error-Message Guidelines',
    by: 'Nielsen Norman Group',
    url: 'https://www.nngroup.com/articles/error-message-guidelines/',
    kind: 'article',
    free: true,
  },
  spaceFramework: {
    title: 'The SPACE of Developer Productivity',
    by: 'Forsgren, Storey, Maddila, Zimmermann, Houck & Butler (ACM Queue)',
    url: 'https://queue.acm.org/detail.cfm?id=3454124',
    kind: 'article',
    free: true,
    note: 'Research framework for measuring developer experience beyond a single number.',
  },
  northStar: {
    title: 'The North Star Playbook',
    by: 'Amplitude',
    url: 'https://amplitude.com/books/north-star',
    kind: 'guide',
    free: true,
    note: 'Choosing the one metric that captures the value developers get from your product.',
  },
  ga4Docs: {
    title: 'Google Analytics Help Center',
    by: 'Google',
    url: 'https://support.google.com/analytics/',
    kind: 'guide',
    free: true,
  },
  orbitModel: {
    title: 'The Orbit Model',
    by: 'Orbit (open source)',
    url: 'https://github.com/orbit-love/orbit-model',
    kind: 'guide',
    free: true,
    note: 'A framework for thinking about community members by love (engagement) and reach.',
  },
  learnInPublic: {
    title: 'Learn In Public',
    by: 'swyx',
    url: 'https://www.swyx.io/learn-in-public',
    kind: 'article',
    free: true,
    note: 'The essay that launched a thousand developer careers. Short. Read it today.',
  },
  jonoCommunity: {
    title: 'Jono Bacon — articles and resources',
    by: 'Jono Bacon',
    url: 'https://www.jonobacon.com/',
    kind: 'article',
    free: true,
  },
  sessionize: {
    title: 'Sessionize',
    by: 'Sessionize',
    url: 'https://sessionize.com/',
    kind: 'tool',
    note: 'Where most tech conferences run their call for papers — create a speaker profile here.',
  },
  papercall: {
    title: 'PaperCall.io',
    by: 'PaperCall',
    url: 'https://www.papercall.io/events',
    kind: 'tool',
    free: true,
    note: 'Browse open CFPs across developer conferences.',
  },
  obs: {
    title: 'OBS Studio',
    by: 'OBS Project',
    url: 'https://obsproject.com/',
    kind: 'tool',
    free: true,
    note: 'Free, open source recording and streaming. The default tool for dev streamers.',
  },
  excalidraw: {
    title: 'Excalidraw',
    by: 'Excalidraw',
    url: 'https://excalidraw.com/',
    kind: 'tool',
    free: true,
    note: 'Hand-drawn style diagrams in seconds — perfect for technical explainers.',
  },
  manim: {
    title: 'Manim Community',
    by: 'Manim Community',
    url: 'https://www.manim.community/',
    kind: 'tool',
    free: true,
    note: 'The Python animation engine behind 3Blue1Brown-style explainers.',
  },
  hemingway: {
    title: 'Hemingway Editor',
    by: 'Hemingway',
    url: 'https://hemingwayapp.com/',
    kind: 'tool',
    note: 'Highlights long sentences and passive voice. A fast editing pass for any draft.',
  },
  valeLinter: {
    title: 'Vale — prose linter',
    by: 'Vale',
    url: 'https://vale.sh/',
    kind: 'tool',
    free: true,
    note: 'Enforce a style guide in CI, the same way you lint code.',
  },
  devTo: {
    title: 'DEV Community',
    by: 'dev.to',
    url: 'https://dev.to/',
    kind: 'community',
    free: true,
    note: 'Low-friction place to publish technical posts and find an audience fast.',
  },
  hashnode: {
    title: 'Hashnode',
    by: 'Hashnode',
    url: 'https://hashnode.com/',
    kind: 'community',
    free: true,
    note: 'Developer blogging on your own domain, with built-in community distribution.',
  },
  freeCodeCampNews: {
    title: 'freeCodeCamp News — write for us',
    by: 'freeCodeCamp',
    url: 'https://www.freecodecamp.org/news/how-to-write-for-freecodecamp/',
    kind: 'guide',
    free: true,
    note: 'Guest-author guidelines for one of the largest developer publications.',
  },
  smashingWrite: {
    title: 'Write for Smashing Magazine',
    by: 'Smashing Magazine',
    url: 'https://www.smashingmagazine.com/write-for-us/',
    kind: 'guide',
    free: true,
  },
  cmx: {
    title: 'CMX — community industry resources',
    by: 'CMX (Bevy)',
    url: 'https://cmxhub.com/',
    kind: 'community',
    free: true,
    note: 'Research, playbooks and events for community professionals.',
  },
  devrelWeekly: {
    title: 'DevRel Weekly',
    by: 'Mary Thengvall',
    // devrelweekly.com was returning a TLS error (Cloudflare 525) in Sept 2026;
    // Mary's site links to the newsletter and stays up.
    url: 'https://www.marythengvall.com/',
    kind: 'newsletter',
    free: true,
    note: 'The weekly roundup of DevRel articles, talks and jobs, curated by Mary Thengvall.',
  },
  devrelCon: {
    title: 'DevRelCon',
    by: 'Hoopy',
    url: 'https://devrelcon.dev/',
    kind: 'community',
    note: 'The main conference for developer relations practitioners.',
  },
  devRelChannel: {
    title: 'DevRelCon talks on YouTube',
    by: 'Dev Rel channel',
    url: 'https://www.youtube.com/c/DevRel',
    kind: 'video',
    free: true,
    note: 'Hundreds of talks from DevRelCon and DevXcon — the deepest free archive of DevRel practice.',
  },
  writeTheDocsChannel: {
    title: 'Write the Docs talks on YouTube',
    by: 'Write the Docs',
    url: 'https://www.youtube.com/@writethedocs',
    kind: 'video',
    free: true,
  },
  communityPulse: {
    title: 'Community Pulse podcast',
    by: 'Jason Lengstorf, PJ Hagerty, Mary Thengvall & Wesley Faulkner',
    url: 'https://www.communitypulse.io/',
    kind: 'podcast',
    free: true,
    note: 'Long-running podcast on developer community and DevRel practice.',
  },

  // ── Videos (verified with YouTube oEmbed by scripts/check-links.mjs) ────────
  vidThengvallWhatIsDevRel: {
    title: 'What is Developer Relations (and why should you care)?',
    by: 'Mary Thengvall',
    url: yt('UgstKIW8bvg'),
    kind: 'video',
    free: true,
  },
  vidThengvallTrends: {
    title: 'Trends in Developer Relations with Mary Thengvall',
    by: 'Mary Thengvall',
    url: yt('FOsv6sSD8OI'),
    kind: 'video',
    free: true,
  },
  vidThengvallBusinessValue: {
    title: 'The Business Value of Developer Relations — Uncommon Book Club',
    by: 'Mary Thengvall',
    url: yt('Z_eHb9TKvKI'),
    kind: 'video',
    free: true,
  },
  vidThengvallCompanyGoals: {
    title: 'First, Understand the Company Goals',
    by: 'Mary Thengvall',
    url: yt('gu9SekOaz18'),
    kind: 'video',
    free: true,
  },
  vidFourPillarsSupport: {
    title: 'The Four Pillars of Support in Developer Relations',
    by: 'Mary Thengvall & K Rain Leander',
    url: yt('P_8DnKN9T0g'),
    kind: 'video',
    free: true,
  },
  vidSpectreMeasuring: {
    title: 'Measuring developer evangelism (DevRelCon SF 2016)',
    by: 'Rob Spectre, Twilio',
    url: yt('fqmFmry9UqA'),
    kind: 'video',
    free: true,
  },
  vidMarketingMetrics: {
    title: 'Learning from marketing to quantify developer relations impact',
    by: 'Kevin Lewis & John Booth (DevRelCon London 2023)',
    url: yt('FATyMAtfvH0'),
    kind: 'video',
    free: true,
  },
  vidMetricsPanel: {
    title: 'DevRelCon Earth 2020 metrics panel',
    by: 'DevRelCon',
    url: yt('D8-vWDInwMk'),
    kind: 'video',
    free: true,
  },
  vidLewkoDxJourney: {
    title: 'Measuring your Developer Experience Journey',
    by: 'Caroline Lewko',
    url: yt('EogvMQMKzH8'),
    kind: 'video',
    free: true,
  },
  vidScalingTeam: {
    title: 'How to scale a developer relations team',
    by: 'Uttam Tripathi',
    url: yt('HKIZowp1rB0'),
    kind: 'video',
    free: true,
  },
  vidDuVanderContent: {
    title: 'How to scale developer relations with content (DevRelCon)',
    by: 'Adam DuVander',
    url: yt('s2WqYMlU4bo'),
    kind: 'video',
    free: true,
  },
  vidDuVanderMarketing: {
    title: 'Developer Marketing Does Not Exist',
    by: 'Adam DuVander',
    url: yt('ocnEZBOkMsY'),
    kind: 'video',
    free: true,
  },
  vidLuffDocs: {
    title: 'Writing Good Documentation for Developers',
    by: 'Meredydd Luff',
    url: yt('eWaWvUhpseM'),
    kind: 'video',
    free: true,
  },
  vidEggerDocs: {
    title: 'Write Docs Devs Love: Ten Tips To Level Up Your Tech Writing',
    by: 'Mason Egger',
    url: yt('9WobKoE9OPI'),
    kind: 'video',
    free: true,
  },
  vidDocsAsCode: {
    title: 'Treating Documentation like Code: a Practical Account',
    by: 'Jodie Putrino (Write the Docs Portland 2017)',
    url: yt('Mzu-c-FoOdw'),
    kind: 'video',
    free: true,
  },
  vidJonoLessons: {
    title: 'Community Lessons Learned the Hard Way',
    by: 'Jono Bacon (Swarm 2020)',
    url: yt('fk1wtCckzgo'),
    kind: 'video',
    free: true,
  },
  vidJonoLeaders: {
    title: 'Building effective community leaders: a guide (DevXcon 2018)',
    by: 'Jono Bacon',
    url: yt('PHHt1I0x8VM'),
    kind: 'video',
    free: true,
  },
  vidJonoIncentives: {
    title: 'Keynote: Smart Incentivization',
    by: 'Jono Bacon',
    url: yt('IFi41eHP2uk'),
    kind: 'video',
    free: true,
  },
  vidDiscordWorkshop: {
    title: 'Running Developer Communities with Discord (Workshop)',
    by: 'Discord',
    url: yt('SlpQrRXuq_w'),
    kind: 'video',
    free: true,
  },
  vidChampions: {
    title: 'Running a developer champions programme (DevRelCon Tokyo 2018)',
    by: 'Matthew Revell & Carla Sofia',
    url: yt('5lVAnZjspVQ'),
    kind: 'video',
    free: true,
  },
  vidChampionProgram: {
    title: 'How to Launch and Manage a Successful Champion Program',
    by: 'Vera Tiago',
    url: yt('Rfbm2ASpyTA'),
    kind: 'video',
    free: true,
  },
  vidCfpWwc: {
    title: 'Writing a Conference Talk Proposal — CFP Speaker Series',
    by: 'Sierra O’Bryan (Women Who Code)',
    url: yt('F-MnEivQfvM'),
    kind: 'video',
    free: true,
  },
  vidCfpCode: {
    title: 'Cracking the CFP Code: How to Write a Standout Conference Proposal',
    by: 'BekahHW & Josh Goldberg',
    url: yt('B48aueFwLL8'),
    kind: 'video',
    free: true,
  },
  vidDuarte: {
    title: 'The Secret Structure of Great Talks (TEDxEast)',
    by: 'Nancy Duarte',
    url: yt('1nYFpuc2Umk'),
    kind: 'video',
    free: true,
  },
  vidTreasure: {
    title: 'How to Speak So That People Want to Listen (TED)',
    by: 'Julian Treasure',
    url: yt('eIho2S0ZahI'),
    kind: 'video',
    free: true,
  },
  vidHightowerDemo: {
    title: 'Kelsey Hightower’s Best Live Demo Yet (Cloud Next ’18)',
    by: 'Kelsey Hightower',
    url: yt('U6SfRPwTKqo'),
    kind: 'video',
    free: true,
  },
  vidHightowerAdvocacy: {
    title: 'Kelsey Hightower on developer advocacy, Kubernetes complexity, and WASM',
    by: 'Kelsey Hightower',
    url: yt('2Q7wjU2Hi4M'),
    kind: 'video',
    free: true,
  },
  vidDoerrOkrs: {
    title: 'Why the secret to success is setting the right goals (TED)',
    by: 'John Doerr',
    url: yt('L4N1q4RNi9I'),
    kind: 'video',
    free: true,
  },
  vidStorytellingData: {
    title: 'Storytelling with Data (Talks at Google)',
    by: 'Cole Nussbaumer Knaflic',
    url: yt('8EMW7io4rSI'),
    kind: 'video',
    free: true,
  },
  vidEghbal: {
    title: 'Working in Public — Open Source, and The Future of The Internet',
    by: 'Nadia Eghbal',
    url: yt('8X89YdZMyrQ'),
    kind: 'video',
    free: true,
  },
  vidLearnInPublic: {
    title: 'Learning in Public with swyx',
    by: 'Shawn "swyx" Wang',
    url: yt('lHG4rNmzQq4'),
    kind: 'video',
    free: true,
  },
  vidGitCrash: {
    title: 'Git and GitHub for Beginners — Crash Course',
    by: 'freeCodeCamp.org',
    url: yt('RGOj5yH7evk'),
    kind: 'video',
    free: true,
  },
  vidApisBeginners: {
    title: 'APIs for Beginners — How to use an API (Full Course)',
    by: 'freeCodeCamp.org',
    url: yt('GZvSYJDk-us'),
    kind: 'video',
    free: true,
  },
  vidGraphql100: {
    title: 'GraphQL Explained in 100 Seconds',
    by: 'Fireship',
    url: yt('eIQh02xuVw4'),
    kind: 'video',
    free: true,
  },
  vidDocker100: {
    title: 'Docker in 100 Seconds',
    by: 'Fireship',
    url: yt('Gjnup-PuquQ'),
    kind: 'video',
    free: true,
  },
  vidK8s100: {
    title: 'Kubernetes Explained in 100 Seconds',
    by: 'Fireship',
    url: yt('PziYflu8cB8'),
    kind: 'video',
    free: true,
  },
  vidServerless100: {
    title: 'Serverless Computing in 100 Seconds',
    by: 'Fireship',
    url: yt('W_VV2Fx32_Y'),
    kind: 'video',
    free: true,
  },
  vidFreemanDx: {
    title: 'What is DX? Creating Great Developer Experience',
    by: 'Emily Freeman',
    url: yt('68YftyceC-g'),
    kind: 'video',
    free: true,
  },
  vidLeRouxDx: {
    title: 'Rethinking Developer Experience (DX)',
    by: 'Brian LeRoux',
    url: yt('gWcXV63es6I'),
    kind: 'video',
    free: true,
  },
  vidBeyondDx: {
    title: 'API Developer Success: Looking Beyond Developer Experience (DX)',
    by: 'Nordic APIs',
    url: yt('-_LlGBuvjZQ'),
    kind: 'video',
    free: true,
  },
  vidOssBeginners: {
    title: 'Getting started with open source contributions for beginners',
    by: 'GitHub',
    url: yt('WldXhauP024'),
    kind: 'video',
    free: true,
  },
  vidLicenses: {
    title: 'Open-Source License Explained in 5 minutes',
    by: 'YouTube explainer',
    url: yt('MjN-mufsNbQ'),
    kind: 'video',
    free: true,
  },
  vidInclusivePortal: {
    title: 'Towards a more inclusive developer portal (DevRelCon SF 2019)',
    by: 'Adam DuVander',
    url: yt('R6Sf34dIImM'),
    kind: 'video',
    free: true,
  },
} satisfies Record<string, Resource>

export type ResourceKey = keyof typeof R
